name: mustache4dart2
version: 0.1.0
author: Georgios Valotasios (Reconfigured by Ross Albertson) <valotas@gmail.com>
description: A mustache implementation for the Dart (2.x) language
homepage: https://github.com/rossalbertson/mustache4dart2
environment:
#  sdk: '>=0.8.10+6 <2.0.0'
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
#  test: '>=0.12.0 <0.12.23'
  test: ^1.0.0
#  isolate: '>=1.0.0 <1.1.0'
  isolate: ^2.0.2
